### ISSUE TITLE
Ability to fetch all teams

### ISSUE THREAD

**Issue by CmdrSharp** [pulumiverse/pulumi-grafana#116]
The provider (and this goes for Terraform as well) currently lacks a way to fetch _all_ teams. It requires specifying a single team to fetch. I would like to see the ability to fetch all teams (with a `getTeams` function, much like `getUsers`). The endpoint `api/teams/search` can be used (with pagination) to accomplish this.

**Comment by ringods** [comment]
@CmdrSharp since this package bridges the Terraform provider, please submit your request in the TF repo:

https://github.com/grafana/terraform-provider-grafana/issues

Once it is implemented upstream, we can take in the new version of the Grafana TF provider.

**Comment by CmdrSharp** [comment]
Makes sense!
Opened up an issue here: https://github.com/grafana/terraform-provider-grafana/issues/1449

Closing this one.
