### ISSUE TITLE
v0.4.0 binary does not start

### ISSUE THREAD

**Issue by kiriwalawren** [pulumiverse/pulumi-grafana#137]
Upon upgrading to `v0.4.0`, the plugin binary can no longer start or load.

![image](https://github.com/pulumiverse/pulumi-grafana/assets/6665964/4f2efad2-f708-4065-b6bf-8212d454db77)

![image](https://github.com/pulumiverse/pulumi-grafana/assets/6665964/635d0a17-cd8e-448e-b64e-d24ce1a30dc5)

**Comment by nanuuki** [comment]
Experiencing this same issue with Go :|

**Comment by ringods** [comment]
Can you all try with v0.4.1 and report your outcome?

**Comment by kiriwalawren** [comment]
That did, in fact, resolve the issue for me! Thank you, kindly!

**Comment by nanuuki** [comment]
@ringods `v0.4.1` works, thank you! :)
