### ISSUE TITLE
pulumi plugin install 403

### ISSUE THREAD

**Issue by artem-zherdiev-ingio** [pulumiverse/pulumi-grafana#17]
Hi, it possible to play with it?

When I try `pulumi plugin install resource grafana v0.0.3` is `error: [resource plugin grafana-0.0.3] downloading from : failed to download plugin: grafana-0.0.3: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-grafana-v0.0.3-linux-amd64.tar.gz` How to deal with it?

Thanks

**Comment by benmcp** [comment]
I get the same error but on Mac, so 403 for `pulumi-resource-grafana-v0.0.3-darwin-arm64.tar.gz`.

Looks like it is stored in an S3 bucket, do we have READ access for these files?

**Comment by aureq** [comment]
If you are stuck on this, it's possible to manually install this Grafana resource provider.

1. Download the archive from the release for your current environment: https://github.com/lbrlabs/pulumi-grafana/releases/tag/v0.0.3 (See https://github.com/lbrlabs/pulumi-grafana/issues/22)
2. Run the following command `pulumi plugin install resource grafana v0.0.3 --file pulumi-resource-scaleway-v0.0.3-linux-amd64.tar.gz` (dont forget to adjust the archive name to match the file you downloaded above)
3. run `pulumi plugin ls` to verify the plugin is installed (as grafana).

**Comment by jaxxstorm** [comment]
I believe this is: https://github.com/pulumi/pulumi/issues/10882

You can install this manually with

```
pulumi plugin install resource grafana v0.0.3 --server github://api.github.com/lbrlabs
```

**Comment by aureq** [comment]
Following the publication if `v0.0.4`, you may install the plugin using the command below

```
pulumi plugin install resource grafana v0.0.4 --server github://api.github.com/lbrlabs
```

**Comment by artem-zherdiev-ingio** [comment]
Thanks, it works!
