### ISSUE TITLE
Nuget gallery is not being updated with latest packages. Still lists v0.5.1 as latest

### ISSUE THREAD

**Issue by robesite** [pulumiverse/pulumi-grafana#213]
Hey team, it seems [npm](https://www.npmjs.com/package/@pulumiverse/grafana) has the latest version(s) but [nuget](https://www.nuget.org/packages/Pulumiverse.Grafana#versions-body-tab) gallery doesn't seem to have anything past v0.5.1. 
Can you please update nuget or am I missing something?

**Comment by ringods** [comment]
@robesite thanks for signalling this. This is indeed wrong.

**Comment by robesite** [comment]
@ringods when should we expect the new versions in [nuget](https://www.nuget.org/packages/Pulumiverse.Grafana)

**Comment by ringods** [comment]
I'm hoping for a fix to land tomorrow in all the repositories I maintain here at Pulumiverse. The Grafana one isn't the only one impacted by this.

**Comment by ringods** [comment]
@robesite publishing of Nuget packages is fixed. I created release v0.9.1.

The Nuget package for it is here:

https://www.nuget.org/packages/Pulumiverse.Grafana/0.9.1
