### ISSUE TITLE
Issue with http_headers in the python sdk

### ISSUE THREAD

**Issue by kevin-lithic** [pulumiverse/pulumi-grafana#27]
We are looking to adopt the plugin but when using the python flavor we are getting an error:
```
    import lbrlabs_pulumi_grafana as grafana
/usr/local/lib/python3.9/site-packages/lbrlabs_pulumi_grafana/__init__.py:56: in <module>
    from .provider import *
E     File "/usr/local/lib/python3.9/site-packages/lbrlabs_pulumi_grafana/provider.py", line 455
E       __props__.__dict__["http_headers"] = None if pulumi.Output.from_input(http_headers).apply(pulumi.runtime.to_json) if http_headers is not None else None is None else pulumi.Output.secret(pulumi.Output.from_input(http_headers).apply(pulumi.runtime.to_json) if http_headers is not None else None)
E                                                                                                                         ^
E   SyntaxError: invalid syntax
```

Looking at the code on that line it doesn't appear to be valid syntax. If we correct it in our local filesystem we are able to get around it and everything works great!

I was taking a look to see if I could resolve the issue. I removed all the references of `http_headers` or `httpHeaders` in `schema.json` and `resources.go` but everything appears to just continue to be overwritten.

**Comment by jaxxstorm** [comment]
Thanks for the report! I'm pushing an update for this now

**Comment by kevin-lithic** [comment]
NICE! Thanks @jaxxstorm will take a look, and follow up if needed!
