### ISSUE TITLE
Add `sdk/{{tag}}` automation

### ISSUE THREAD

**Issue by jaxxstorm** [pulumiverse/pulumi-grafana#69]
When we create a new release, we need to add a `sdk/{{tag}}` tag for the Go SDK.

We need this to be automated so our intrepid maintainer doesn't forget

**Comment by nanuuki** [comment]
ping @jaxxstorm @ringods 

~~could we get an `sdk/v0.4.0` tag for the latest release? :)  (#137 seems related)~~

----

Update; `sdk/v0.4.1` tag was added, thank you :)

**Comment by ringods** [comment]
With the rollout of https://github.com/pulumi/ci-mgmt/ for GHA workflow automation, this is now fixed in a consistent way.

https://github.com/pulumiverse/pulumi-grafana/commit/cc7fe8702e2dbc5da12cfc72fb60c797262895b6
