### ISSUE TITLE
Provider does not work when auth is set via GRAFANA_AUTH and url is set in my code

### ISSUE THREAD

**Issue by jackryan683** [pulumiverse/pulumi-grafana#83]
I was able to get the Grafana Provider to work when I set GRAFANA_AUTH and GRAFANA_URL as env vars on my linux machine. I can also get it to work when I have both values in my code:
new grafana.Provider("provider", 
{
    auth: "test",
    url: "test",
});

The issue occurs when I split it up. So I have GRAFANA_AUTH an an env var and then the url in my code.

**Comment by jackryan683** [comment]
https://www.pulumi.com/registry/packages/grafana/api-docs/provider/

**Comment by jaxxstorm** [comment]
I believe this is now resolved, as show in #85
