### ISSUE TITLE
Is there a resource for an alert Rule?

### ISSUE THREAD

**Issue by bsod90** [pulumiverse/pulumi-grafana#98]
Hi, pulumi-grafana authors!
I'm trying to automatically configure some grafana alerts for my infra, but following the official doc I could only find a `RuleGroup` resource, which is not exactly the same thing as a singular alert.
I'm wondering if I'm missing something or if there's a reason it's not implemented.

<img width="852" alt="Screenshot 2023-07-11 at 3 10 45 PM" src="https://github.com/lbrlabs/pulumi-grafana/assets/2292499/9345bfc1-70b2-4e10-b97f-bc58ebee778c">

Thanks for any help!

**Comment by ringods** [comment]
Hello @bsod90, we aren't actually authoring any resources ourselves in this provider. We bridge the [upstream Terraform provider](https://github.com/grafana/terraform-provider-grafana). If you are missing a resource, please submit an issue in the upstream TF provider. Once it is implemented there, we can easily expose it here too.
